name: kite_page
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  dynamic_color_theme: ^2.0.0
  flutter_easyloading: ^3.0.5
  flutter_weather_bg_null_safety: ^1.0.0  # Weather background
  flutter_screenutil: ^5.5.4
  catcher: ^0.6.9
  universal_platform: ^1.0.0+1
  json_annotation: ^4.6.0
  dio: ^4.0.6
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.1.5
  flutter_svg: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

flutter:

  uses-material-design: true

  fonts:
    # Iconfont for ywb.sit.edu.cn
    # For office module. So I named it office_iconfont.
    - family: office_iconfont
      fonts: [{ asset: assets/fonts/office_iconfont.ttf }]

    # Good night module
    - family: calligraphy
      fonts: [{ asset: assets/fonts/calligraphy.ttf }]

  assets:
    - assets/
    - assets/welcome/
    - assets/fonts/

flutter_native_splash:
  fullscreen: true
  color: '#FFFFFF'
  image: assets/icon.png